baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "Darshan Baral"
    description = "Martin Frigaard dot io"
    copyright = "Martin James Frigaard"

    [params.theme]
        allowToggle = true
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        altTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Martin Frigaard, MA, MAS"
		tagline = "Data Scientist, Co-Founder"
		location = "Oakland, CA"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/mjfrigaard/"
            title = "LinkedIn"		
        #[[params.social.list]]
        #    class = "fab"
        #    icon = "fa-stack-overflow"
        #    url = "#"
        #    title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/mjfrigaard"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/mjfrigaard"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar"
            url = "http://bit.ly/goo-schlr-mjfrigaard"
            title = "Google Scholar"
		#[[params.social.list]]
        #    class = "ai"
        #    icon = "ai-researchgate"
        #    url = "#"
        #    title = "ResearchGate"

    #Specify what is showin in the Accordion  ---------------------------------
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**Hi! I'm Martin Frigaard**, a Data Scientist and Co-Founder of Paradigm Datagroup. I provide workshops, write guides and tutorials, and build web applications for individuals and teams working with data. I've been performing statistical analyses and creating data visualizations with R for 7 years. [I'm also a fully certified RStudio `tidyverse` trainer.](https://education.rstudio.com/trainers/)"

    # Experience section  ------------------------------------------------------
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Data Scientst, Co-Founder"
            dates = "2019 - *Present*"
            company = "Paradigm Data Group"
            link = "https://www.paradigmdata.io/"
            details = "Our company provides data science trainings and solutions to companies, schools, teams, and individuals."
        [[params.experience.list]]
            position = "Author/Contributor"
            dates = "2019 - *Present*"
            company = "Storybench"
            link = "[Data Journalism in R](http://www.storybench.org/category/data-journalism-in-r/)"
            details = "These are a series of tutorials I write for journalists looking to learn R."
        [[params.experience.list]]
            position = "Computational & Data Science Research Specialist III"
            dates = "2017 - 2018"
            link = "https://www.ucsf.edu/research"
            company = "University of California, San Francisco"
            details = "I was responsible for analyzing existing software, scientific code, data science/analytics code/algorithms and applied complex programming practices. I also worked with domain scientists where applicable to perform these responsibilities and uses domain science knowledge where relevant."
        [[params.experience.list]]
            position = "Researcher Associate"
            dates = "2015 - 2017"
            company = "NCIRE - The Veterans Health Research Initiative"
            link = "[Implementation of a pragmatic randomized trial of screening for chronic kidney disease to improve care among non-diabetic hypertensive veterans](https://bmcnephrol.biomedcentral.com/articles/10.1186/s12882-017-0541-6)"
            details = "As the Research Associate, I was responsible for the data management of all clinical research volunteers (physicians and clinical pharmacists) and subjects (trial participants) to ensure veterans were screened or diagnosed with chronic kidney disease."  

    # Education section --------------------------------------------------------
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "M.A.S. in Clinical Research"
            college = "University of California, San Francisco"
            dates = "2015 - 2017"
            thesis_title = "Validating laboratory defined chronic kidney disease in the electronic health record for patients in primary care"
            thesis_link = "https://bmcnephrol.biomedcentral.com/articles/10.1186/s12882-018-1156-2"
        [[params.education.list]]
            degree = "M.A. in Kinesiology"
            college = "California State University, Chico"
            dates = "2009 - 2011"
            thesis_title = "Associations Between Obesity and Elevated Blood Pressure Among Children in Five Low-Income Northern California Elementary Schools"
            thesis_link = "http://csuchico-dspace.calstate.edu/handle/10211.3/10211.4_387"
        [[params.education.list]]
            degree = "B.S. in Exercise Physiology"
            college = "California State University, Chico"
            dates = "2007 - 2009"

    # Publication section  -----------------------------------------------------
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Posters & Abstracts"]

        [[params.publication.list]]
            title = "Implementation of a pragmatic randomized trial of screening for chronic kidney disease to improve care among non-diabetic hypertensive veterans."
            authors = "CA Peralta, M Frigaard, AD Rubinsky, L Rolon, L Lo, S Voora, K Seal, D Tuot, S Chao, K Lui, P Chiao, N Powe, M Shlipak."
            date = "2017"
            journal = "BMC Nephrology. 2017 Apr 12;18(1):132."
            link = "https://www.ncbi.nlm.nih.gov/pubmed/28399844"
            type = "Journal Articles"
            
        [[params.publication.list]]
            title = "Identifying Red Flags: Using Anthropometry Measures to Screen for Elevated Blood Pressure Risk in Children"
            authors = "M Frigaard, K Goto, C Wolff, S Bianco-Simeral, T Fahey"
            date = "2013"
            journal = "Childhood Obesity and Nutrition. January 14, 2013"
            link = "https://journals.sagepub.com/doi/10.1177/1941406412470719"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "The Associations Between Ckd Diagnosis And Guideline-Driven Care"
            authors = "MJ Frigaard, L Karliner, C Peralta"
            date = "2018"
            journal = "American Journal Of Kidney Diseases 71 (4), 539-539"
            link = "https://www.ajkd.org/article/S0272-6386(18)30232-4/fulltext"
            type = "Posters & Abstracts"
		
        [[params.publication.list]]
            title = "Comparison Of Historical Lab-Ckd And Clinician Chart Review."
            authors = "M Frigaard, C Peralta, L Karliner"
            date = "2018"
            journal = "American Journal Of Kidney Diseases 71 (4), 539-539"
            link = "https://www.ajkd.org/article/S0272-6386(18)30231-2/fulltext"
            type = "Posters & Abstracts"

    # Project section  --------------------------------------------------------
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Sharing your work"
            url = "https://leanpub.com/showingyourwork/"
            description = "This is a free text I wrote for our business partners. It covers getting started in R, RStudio & Git and sharing a project with Github pages. I covered these topics with a relevant case study (2020 democratic candidates Google trend and Twitter data)."
        [[params.project.list]]
            title = "The Diabetes Technology Society Blood Glucose Monitor System (BGMS) Surveillance Program"
            url = "https://www.diabetestechnology.org/seg/"
            description = "The error grids clinicians use to check the accuracy of blood glucose monitors are out-of-date. Regulatory agencies don't use error grids for approving monitors, but these tools could be useful for testing the performance of recommended products. The Diabetes Technology Society partnered with representatives from the Food and Drug Administration, the American Diabetes Association, the Endocrine Society, and the Association for the Advancement of Medical Instrumentation, and representatives from academia, industry, and government developed the surveillance error grid (SEG) as a tool to assess the degree of clinical risk from inaccurate blood glucose monitors (BGM). I built a Shiny app for clinicians to import data from a BGM, perform statistical tests for accuracy, and create data visualizations to communicate the results."

    # Skill section --------------------------------------------------------
    
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "R Programming, Data visualization"
            skillrating = 90
        [[params.skill.list]]
            skill = "Science Communication"
            skillrating = 80
        [[params.skill.list]]
            skill = "Web Technologies"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Krav Maga"
        [[params.hobby.list]]		
		    hobby = "Hiking & Camping"
        [[params.hobby.list]]		
		    hobby = "BBQ"
